### ISSUE TITLE
parse_pkcs11_uri is incomplete and not compliant with RFC 7512

### ISSUE THREAD

**Issue by dengert** [OpenSC/engine_pkcs11#28] opened 2015-12-18 15:21 UTC
See: 
 https://www.mail-archive.com/openssl-dev@openssl.org/msg41245.html

The parse_pkcs11_uri in engine_pkcs11.c does not parse all the possible options even if they are to be ignored. 
In particular, type= is ignored, but only if it has 2 of the 5 possible values. type=public produces an error: 
"The key ID is not a valid PKCS#11 URI as defined by RFC7512"

it looks like type could be "public" / "private" / "cert" / "secret-key" / "data"
It also looks like  parse_pkcs11_uri will fail to parse  the "library-", "slot-",  "model-" 
and "'pin-source" attributes. 

The above message is very misleading, as it imples it is parsing according to RFC 7512
but it is not. 

I have no good way to test this.

**Comment by nmav** [comment] 2015-12-18 15:45
Indeed, it seems that 'public' key types are not properly handled. I've added a quick fix, but we certainly need a test case for that. I'm leaving this issue open until a test case is present.

**Comment by dengert** [comment] 2015-12-18 17:56
@mouse07410 This is your problem, can you work with @nmav to test it?

**Comment by mouse07410** [comment] 2015-12-18 20:17
@dengert, I'll certainly be happy to work with Nikos getting this fixed & tested.

@nmav, the only fix I saw prevented the code from returning `rv=0` on the spot for `object-type=public`. But in the end the key (or certificate) is not returned, and the "standard" error message is printed:
```
openssl rsautl -engine pkcs11 -keyform engine -verify -inkey "pkcs11:object=SIGN%20pubkey;object-type=public" -pubin -pkcs -in sig1.out < ~/src/wtls-verifier
engine "pkcs11" set.
PKCS#11 token PIN: 
key not found.
PKCS11_load_public_key returned NULL
unable to load Public Key
```

The above happens regardless of the object type. I tried `object-type=cert` (with the corresponding change of the URI of course), and omitting `object-type` completely. The very same error message.

Here's an excerpt from my post to openssl-dev:

> I suspect (Doug and Nikos, please correct if I’m wrong!) that since many tokens (mine certainly)
> do not perform operations with the public keys, when a public key on the token is referred – it needs
> to be retrieved and processed entirely in software. So the key needs to be retrieved from the card
> somehow, and passed to the other components of pkeyutl, rsautl, or dgst…
>
> What would be a good location in the code for that addition?

**Comment by dengert** [comment] 2015-12-18 22:16
This will read the pubkey as PEM:
pkcs15-tool --read-public-key $1 -o /tmp/pubkey

Or pkcs11-tool --module ...   -slot 1  -r -d 02 -y pubkey  > /tmp/pubkey.der


Or  something like:
openssl pkey -engine pkcs11 -inform engine -in id_02 -text

Not sure whaich will work with the uri.

**Comment by mouse07410** [comment] 2015-12-19 02:01
Yes the way @dengert showed certainly works:
1. `pkcs11-tool -r -y pubkey -d 02 -o pubkey.der` would output the public key from Digital Signature slot in DER format.
2. `pkcs15-tool --read-public-key 02 -o pubkey.pem` would output that public key in PEM format.
3.  `openssl pkey -engine pkcs11 -inform engine -in id_02 -text -noout` also works, and outputs public key as Modulus and Exponent.

(3) demonstrates that there already is a way to get the public key from within OpenSSL + pkcs11_engine. 

I have a few demo/test scripts that utilize the "split" approach ((1) or (2) plus openssl) - one command (usually from the OpenSC cli set) extracts the key into a local file, then OpenSSL cli use that key to verify, or such... I would still prefer to get the OpenSSL-only mechanism fixed and fully operational (employing *engine_pkcs11*, of course).

One concern: all of the above keep asking for the PIN. It is unclear why one would need a PIN to do anything with a **public** key (as opposed to the operations with a **private** key). If possible, it would be nice to remedy this.

And we still need to figure why `openssl dgst ...` cannot access/use the public key the way (3) above does. @nmav do you have any idea what's going on, and how to remedy this?

**Comment by dengert** [comment] 2015-12-19 03:20
Its like mixing apples and oranges. 

PKCS#11 treats a private key as seperate from a public key (with same ID on both to match them up).
OpenSSL treats a key as having both a private and public part, The private part contains the public part.

The PIN is a PKCS#11/smartcard thing usually need only to use the private key. OpenSSL does not use PINs, but will pass along. 

You said:
"And we still need to figure why  openssl dgst ...  cannot access/use the public key the way" 
steve@openssl.org on 12/10/15 gave a good explaination. (He is one of the top OpenSSL developers,
listing to him.)

**Comment by mouse07410** [comment] 2015-12-19 23:49
> Its like mixing apples and oranges.

Never claimed proficiency, nor deep understanding.

> steve@openssl.org on 12/10/15 gave a good explanation.

Could you please post a pointer to the explanation itself? And is that Steve by any chance Steve Henson?

**Comment by dengert** [comment] 2015-12-20 02:55
It was Sr. Stephen Henson in response to your OpenSSL post:
    
http://openssl.6102.n7.nabble.com/openssl-pkeyutl-unable-to-use-keys-on-a-PKCS11-token-tt61570.html#none
    
    On 12/19/2015 5:49 PM, Mouse wrote:
    
    
      
        Its like mixing apples and oranges.
      
      Never claimed proficiency, nor deep understanding.
      
        steve@openssl.org
          on 12/10/15 gave a good explanation.
      
      Could you please post a pointer to the explanation itself? And
        is that Steve by any chance Steve Henson?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by nmav** [comment] 2015-12-20 09:52
> One concern: all of the above keep asking for the PIN. It is unclear why one would need a PIN to do 
> anything with a public key (as opposed to the operations with a private key). If possible, it would be 
> nice to remedy this.

A public key object could be marked as sensitive, and in that case a PIN will be required. Some tokens (like softhsm), mark public keys as senstive by default. If that's not the case, we'll have to check that further.

> And we still need to figure why openssl dgst ... cannot access/use the public key the way (3) above
> does. @nmav do you have any idea what's going on, and how to remedy this?

No idea. I'm currently on holidays and cannot followup. I'll try to schedule to look at that in January.

**Comment by mouse07410** [comment] 2015-12-20 16:03
> A public key object could be marked as sensitive, and in that case a PIN will be required.

I see. Thanks!  It does look like some *public keys* are marked sensitive, while *certificates* are not.
For example:
```
$ p11tool --provider=/Library/OpenSC/lib/opensc-pkcs11.so --list-all
Object 0:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=1e00100269d78e66;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%01;object=PIV%20AUTH%20pubkey;object-type=public
	Type: Public key
	Label: PIV AUTH pubkey
	Flags: CKA_WRAP/UNWRAP; CKA_SENSITIVE;
	ID: 01

Object 1:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=1e00100269d78e66;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%01;object=Certificate%20for%20PIV%20Authentication;object-type=cert
	Type: X.509 Certificate
	Label: Certificate for PIV Authentication
	ID: 01

Object 2:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=1e00100269d78e66;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%02;object=SIGN%20pubkey;object-type=public
	Type: Public key
	Label: SIGN pubkey
	Flags: CKA_SENSITIVE;
	ID: 02

Object 3:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=1e00100269d78e66;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%02;object=Certificate%20for%20Digital%20Signature;object-type=cert
	Type: X.509 Certificate
	Label: Certificate for Digital Signature
	ID: 02
```

When you're back, could we try to work out a solution that would use certificates (extracting public keys from them)?

Also, for some reason referring to the public key by its ID (like `id_02`) appears to work, while referring by its URL does not (see my previous posts). I don't think it's correct? Could we address this too?

Thanks!

**Comment by dengert** [comment] 2015-12-20 21:14
pkcs15_pubkey_get_attribute in OpenSC  ./pkcs11/framework-pkcs15.c
    has:
    
    3880         case CKA_SENSITIVE:
    3881                 check_attribute_buffer(attr, sizeof(CK_BBOOL));
    3882                 *(CK_BBOOL*)attr->pValue = TRUE;
    3883                 break;
    
    looks like it always returns TRUE for a pubkey. 
    But PKCS#11 v2.20 says  CKA_SENSITIVE is only an attribute for
    private keys. 
    So OpenSC should consider a query of a pubkey for CKA_SENSITIVE to
    be an invalid attribute query.
    
    So why is p11tool listing CKA_SENSITIVE as a flag for pubkey?
    
    CKA_PRIVATE on the other hand is a attribute for any object:
    "When the CKA_PRIVATE attribute is CK_TRUE, a user may not access
    the object
    until the user has been authenticated to the token."
    
    So some program may be looking at the wrong attribute. 
    
    On 12/20/2015 10:03 AM, Mouse wrote:
    
    
      
        A public key object could be marked as sensitive, and in that
          case a PIN will be required.
      
      I see. Thanks! It does look like some public keys are
        marked sensitive, while certificates are not.
        For example:
      $ p11tool --provider=/Library/OpenSC/lib/opensc-pkcs11.so --list-all
Object 0:
    URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=1e00100269d78e66;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%01;object=PIV%20AUTH%20pubkey;object-type=public
    Type: Public key
    Label: PIV AUTH pubkey
    Flags: CKA_WRAP/UNWRAP; CKA_SENSITIVE;
    ID: 01

Object 1:
    URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=1e00100269d78e66;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%01;object=Certificate%20for%20PIV%20Authentication;object-type=cert
    Type: X.509 Certificate
    Label: Certificate for PIV Authentication
    ID: 01

Object 2:
    URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=1e00100269d78e66;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%02;object=SIGN%20pubkey;object-type=public
    Type: Public key
    Label: SIGN pubkey
    Flags: CKA_SENSITIVE;
    ID: 02

Object 3:
    URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=1e00100269d78e66;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%02;object=Certificate%20for%20Digital%20Signature;object-type=cert
    Type: X.509 Certificate
    Label: Certificate for Digital Signature
    ID: 02

      When you're back, could we try to work out a solution that
        would use certificates (extracting public keys from them)?
      Also, for some reason referring to the public key by its ID
        (like id_02) appears to work, while referring by
        its URL does not (see my previous posts). I don't think it's
        correct? Could we address this too?
      Thanks!
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment] 2015-12-21 02:58
@dengert, I think you pinpointed the bug. Who could fix it, and how?

Here's the `pkcs15-tool` output, in case it helps.

```
$ pkcs15-tool --list-public-keys
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
Public RSA Key [PIV AUTH pubkey]
	Object Flags   : [0x0]
	Usage          : [0xD1], encrypt, wrap, verify, verifyRecover
	Access Flags   : [0x2], extract
	ModLength      : 2048
	Key ref        : 154 (0x9A)
	Native         : yes
	Auth ID        : 01
	ID             : 01
	DirectValue    : <absent>

Public RSA Key [SIGN pubkey]
	Object Flags   : [0x0]
	Usage          : [0x2C1], encrypt, verify, verifyRecover, nonRepudiation
	Access Flags   : [0x2], extract
	ModLength      : 2048
	Key ref        : 156 (0x9C)
	Native         : yes
	Auth ID        : 01
	ID             : 02
	DirectValue    : <absent>

Public RSA Key [KEY MAN pubkey]
	Object Flags   : [0x0]
	Usage          : [0x11], encrypt, wrap
	Access Flags   : [0x2], extract
	ModLength      : 2048
	Key ref        : 157 (0x9D)
	Native         : yes
	Auth ID        : 01
	ID             : 03
	DirectValue    : <absent>

Public RSA Key [CARD AUTH pubkey]
	Object Flags   : [0x0]
	Usage          : [0xC0], verify, verifyRecover
	Access Flags   : [0x2], extract
	ModLength      : 2048
	Key ref        : 158 (0x9E)
	Native         : yes
	Auth ID        : 00
	ID             : 04
	DirectValue    : <absent>

$ pkcs15-tool -c
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
X.509 Certificate [Certificate for PIV Authentication]
	Object Flags   : [0x0]
	Authority      : no
	Path           :
	ID             : 01
	Encoded serial : 02 04 xxxxxxxx
X.509 Certificate [Certificate for Digital Signature]
	Object Flags   : [0x0]
	Authority      : no
	Path           :
	ID             : 02
	Encoded serial : 02 04 xxxxxxxx
X.509 Certificate [Certificate for Key Management]
	Object Flags   : [0x0]
	Authority      : no
	Path           :
	ID             : 03
	Encoded serial : 02 04 xxxxxxxx
X.509 Certificate [Certificate for Card Authentication]
	Object Flags   : [0x0]
	Authority      : no
	Path           :
	ID             : 04
	Encoded serial : 02 04 xxxxxxxx
```

**Comment by mouse07410** [comment] 2015-12-21 03:58
1. I think the following patch should address one part of the problem:

```
diff --git a/src/pkcs11/framework-pkcs15.c b/src/pkcs11/framework-pkcs15.c
index e103550..89e811d 100644
--- a/src/pkcs11/framework-pkcs15.c
+++ b/src/pkcs11/framework-pkcs15.c
@@ -3880,8 +3880,13 @@ pkcs15_pubkey_get_attribute(struct sc_pkcs11_session *session, void *object, CK_
        case CKA_TOKEN:
        case CKA_SENSITIVE:
                check_attribute_buffer(attr, sizeof(CK_BBOOL));
-               *(CK_BBOOL*)attr->pValue = TRUE;
-               break;
+               if (pubkey->pub_p15obj)
+                       *(CK_BBOOL*)attr->pValue = (pubkey->pub_p15obj->flags & SC_PKCS15_PIN_FLAG_CASE_SENSITIVE) != 0;
+               else if (cert && cert->cert_p15obj)
+                       *(CK_BBOOL*)attr->pValue = (cert->pub_p15obj->flags & SC_PKCS15_PIN_FLAG_CASE_SENSITIVE) != 0;
+               else
+                       return CKR_ATTRIBUTE_TYPE_INVALID;
+               break;
        case CKA_LOCAL:
                check_attribute_buffer(attr, sizeof(CK_BBOOL));
                if (pubkey->pub_info)
```

2. I think the following code in `src/tools/pkcs15-tool.c` around line 673 is probematic, as it always requires to authenticate the card for public key retrieval. What is your opinion?
 
```
static int read_public_key(void)
{
	int r;
	struct sc_pkcs15_id id;
	struct sc_pkcs15_object *obj;
	sc_pkcs15_pubkey_t *pubkey = NULL;
	sc_pkcs15_cert_t *cert = NULL;
	sc_pkcs15_der_t pem_key;

	pem_key.value = NULL;
	pem_key.len = 0;

	id.len = SC_PKCS15_MAX_ID_SIZE;
	sc_pkcs15_hex_string_to_id(opt_pubkey, &id);

	r = sc_pkcs15_find_pubkey_by_id(p15card, &id, &obj);
	if (r >= 0) {
		if (verbose)
			printf("Reading public key with ID '%s'\n", opt_pubkey);
		r = authenticate(obj);
		if (r >= 0)
			r = sc_pkcs15_read_pubkey(p15card, obj, &pubkey);
	} else if (r == SC_ERROR_OBJECT_NOT_FOUND) {
		/* No pubkey - try if there's a certificate */
```

**Comment by dengert** [comment] 2015-12-21 16:10
I think you are barking up the wrong tree. 
PKCS#11 only lists CKA_SENSITIVE for CKO_SECRET_KEY and CKO_PRIVATE_KEY.

Is libp11 testing the wrong attribute or not even testing for CKA_PRIVATE?
Is it assuming the pin is needed for any key?
This may be the main problem.

Your change may work, but there are many issues here and this is the wrong mailing list to address OpenSC PKCS#11 issues. 

Why does p11tool show CKA_SENSITIVE for a public key?
Why does OpenSC return CKA_SENSITIVE = TRUE  for a CKO_PUBLIC_KEY?
(Both may be some compatablity issues with some old not PKCS#11 compliant software...)

I would not accept your change at this point. and this is the wrong list to propose these changes.

**Comment by mouse07410** [comment] 2015-12-21 22:03
> I think you are barking up the wrong tree. 

Why so?  The problem is several software packages mark public keys as CKA_SENSITIVE, which in turn requires PIN prompt to access them. `engine_pkcs11` is one of them. `pkcs15-tool` is the other.
So I'm submitting PRs for both. 

> PKCS#11 only lists CKA_SENSITIVE for CKO_SECRET_KEY and CKO_PRIVATE_KEY.

And this is exactly why the current behavior of both `engine_pkcs11` (impacting openssl and gnutls) and `pkcs15-tool` (impacting OpenSC) is wrong.

> Is libp11 testing the wrong attribute or not even testing for CKA_PRIVATE?

I think the attribute gets set by `engine_pkcs11` after the key is retrieved, unconditionally (if/when the attribute is checked). 

> Your change may work, but there are many issues here and this is the wrong mailing list
> to address OpenSC PKCS#11 issues.

My apologies. Could you please point me at the right place to continue this? As I said, the problem is in two places:
1. pkcs15-tool.c and framework-pkcs15.c (both are components of OpenSC);
2. engine_pkcs11.c (main component of engine_pkcs11).

> Why does p11tool show CKA_SENSITIVE for a public key?
> Why does OpenSC return CKA_SENSITIVE = TRUE for a CKO_PUBLIC_KEY?
> (Both may be some compatablity issues with some old not PKCS#11 compliant software...)

Not being around when that code was written (presumably long time ago), I don't have the slightest idea. Somebody made a mistake, and others copied it? Somebody tried to be compatible with some weird not-existing-any-more stuff? Somebody just did not read the standard? Your guess would be much better than mine here.

Note that with the PR (soon to appear) for `engine_pkcs11` p11tool stops (incorrectly) marking public keys as CKA_SENSITIVE (but correctly keeps marking **private** keys as CKA_SENSITIVE, which means they cannot leave hardware):
```
$ p11tool --provider=/Library/OpenSC/lib/opensc-pkcs11.so --list-all
Object 0:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=6d87283aaed2e6a5;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%01;object=PIV%20AUTH%20pubkey;object-type=public
	Type: Public key
	Label: PIV AUTH pubkey
	Flags: CKA_WRAP/UNWRAP; 
	ID: 01

Object 1:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=6d87283aaed2e6a5;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%01;object=Certificate%20for%20PIV%20Authentication;object-type=cert
	Type: X.509 Certificate
	Label: Certificate for PIV Authentication
	ID: 01

Object 2:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=6d87283aaed2e6a5;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%02;object=SIGN%20pubkey;object-type=public
	Type: Public key
	Label: SIGN pubkey
	ID: 02

Object 3:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=6d87283aaed2e6a5;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%02;object=Certificate%20for%20Digital%20Signature;object-type=cert
	Type: X.509 Certificate
	Label: Certificate for Digital Signature
	ID: 02

Object 4:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=6d87283aaed2e6a5;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%03;object=KEY%20MAN%20pubkey;object-type=public
	Type: Public key
	Label: KEY MAN pubkey
	Flags: CKA_WRAP/UNWRAP; 
	ID: 03

Object 5:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=6d87283aaed2e6a5;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%03;object=Certificate%20for%20Key%20Management;object-type=cert
	Type: X.509 Certificate
	Label: Certificate for Key Management
	ID: 03

Object 6:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=6d87283aaed2e6a5;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29;id=%04;object=CARD%20AUTH%20key;object-type=private
	Type: Private key
	Label: CARD AUTH key
	Flags: CKA_SENSITIVE; 
	ID: 04
```

And here's the PR:
https://github.com/OpenSC/engine_pkcs11/pull/30

> I would not accept your change at this point. 

Please reconsider.

> and this is the wrong list to propose these changes.

I've submitted PRs to the appropriate Github repos, I think. Please feel free to correct me, if I'm wrong.

**Comment by mtrojnar** [comment] 2016-01-08 10:25
The https://www.rfc-editor.org/rfc/rfc7512.txt parser is indeed incomplete.  I will fix it.

**Comment by mtrojnar** [comment] 2017-03-18 11:14
Both "type=public" handling and accessing public keys or certificates that require PIN are now fixed.  I am closing this issue.  Please open additional issues in libp11 for any other incompatibilities.

Specifically, handling "module-name" and "module-path" attributes would require loading a module each time a new key handle is requested.  This does not sound like a good idea.

**Closed by mtrojnar** 2017-03-18 11:14 UTC
Labels: bug
